name: On Version Tagged, Build and Publish Rust Binaries
on:
  push:
    tags:
    - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    uses: harmony-labs/workflows-rust/.github/workflows/release.yaml@v1.0.0
    with:
      binary_name: ${{ github.event.repository.name }}
      build_args: "--release --features vendored"
      runs-on: |
        [
          {
            "runs-on": "runs-on=${{ github.run_id }}", 
            "runner": "2cpu-linux-x64", 
            "extras": "s3-cache", 
            "target": "x86_64-unknown-freebsd"
          },
          {
            "runs-on": "runs-on=${{ github.run_id }}",
            "runner": "2cpu-linux-x64",
            "extras": "s3-cache",
            "target": "x86_64-unknown-linux-musl"
          },
          {
            "runs-on": "runs-on=${{ github.run_id }}",
            "runner": "2cpu-linux-arm64",
            "extras": "s3-cache",
            "target": "arm-unknown-linux-musleabi"},
          {
            "runs-on": "runs-on=${{ github.run_id }}",
            "runner": "2cpu-linux-x64",
            "extras": "s3-cache",
            "target": "i686-unknown-linux-musl"
          },
          {
            "runs-on": "macOS-latest",
            "target": "x86_64-apple-darwin"
          },
          {
            "runs-on": "macOS-latest",
            "target": "aarch64-apple-darwin"
          },
          {
            "runs-on": "runs-on=${{ github.run_id }}",
            "image": "windows22-base-x64",
            "family": "m7i",
            "target": "i686-pc-windows-msvc"
          },
          {
            "runs-on": "runs-on=${{ github.run_id }}",
            "image": "windows22-base-x64",
            "family": "m7i",
            "target": "aarch64-pc-windows-msvc"
          },
          {
            "runs-on": "runs-on=${{ github.run_id }}",
            "image": "windows22-base-x64",
            "family": "m7i",
            "target": "x86_64-pc-windows-msvc"}
        ]
